// <auto-generated />
namespace JuntaApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OverrideConventions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverrideConventions));
        
        string IMigrationMetadata.Id
        {
            get { return "201909150457454_OverrideConventions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
